name : resnet18_sngp
train_batch_size: 64
predict_batch_size: 256
n_epochs: 250
spectral_norm:
  use_spectral_norm: True
  norm_bound: 6
  n_power_iterations: 1
gp:
  kernel_scale: 1
  num_inducing: 1024
  normalize_input: False
  random_feature_type: orf
  scale_random_features: False
  cov_momentum: -1
  ridge_penalty: 1
  mean_field_factor: 75
optimizer:
  lr: 0.1
  weight_decay: 0.0005
  momentum: .9