name : resnet18_sngp
# dropout_rate: 0.1
spectral_norm:
  use_spectral_norm: True
  coeff: 6
  n_power_iterations: 1
gp:
  kernel_scale: 1
  num_inducing: 1024
  normalize_input: False
  scale_random_features: False
  cov_momentum: -1
  ridge_penalty: 1
  mean_field_factor: 20 # pi / 8
optimizer:
  lr: 0.08
  weight_decay: 3e-4
  momentum: .9