name: sghmc
backbone: resnet18
ensemble: 
  n_snapshots: 20
  warm_up_batches: 100
optimizer:
  auto_params: True
  lr: 0.01
  C: 10
  B_estim: 9
  resample_each: 1000000000
  lr_gamma: 0.2
  lr_step_epochs: [60, 120, 160]