name : sngp
backbone: resnet18_spectral_norm
# Spectral norm args
use_spectral_norm: True
coeff: 6
n_power_iterations: 1
# GP args
kernel_scale: 1
num_inducing: 1024
normalize_input: False
ridge_penalty: 1
cov_momentum: -1
mean_field_factor: 20
# Optimizer args
lr: 0.08
weight_decay: 3e-4
momentum: .9
lr_gamma: 0.2
lr_step_size: 60