name : sngp
backbone: spectral_wide_resnet_28_10
dropout_rate: .1
spectral_norm:
  use_spectral_norm: True
  coeff: 6
  n_power_iterations: 1
gp:
  kernel_scale: 1
  num_inducing: 1024
  normalize_input: False
  scale_random_features: False
  cov_momentum: -1
  ridge_penalty: 1
  mean_field_factor: 20
optimizer:
  lr: 0.08
  weight_decay: 3e-4
  momentum: .9
  lr_gamma: 0.2
  lr_step_epochs: [60, 120, 160]