name : wideresnet2810_sngp
batch_size: 64
n_epochs: 250
dropout_rate: 0.1
spectral_norm:
  use_spectral_norm: True
  norm_bound: 6
  n_power_iterations: 1
gp:
  kernel_scale: 400
  num_inducing: 1024
  normalize_input: False
  random_feature_type: orf
  scale_random_features: False
  cov_momentum: -1
  ridge_penalty: 1
  mean_field_factor: 1 # 0.3927
optimizer:
  lr: 0.08
  weight_decay: 3e-4
  momentum: .9