defaults:
  - _self_
  - model: resnet18
  - dataset: CIFAR10


random_seed: 42
dataset_path: ./data/
val_interval: 25

output_dir: ./output/
hydra:
  run:
    dir: ${output_dir}
  job_logging:
    handlers:
      file:
        mode: w

