random_seed: 42
experiment_name: batch_al
mlflow_uri: sqlite:///active_learning.db

dataset_path: /home/datasets
imagenet_path: /mnt/datasets/imagenet/ILSVRC2012/
dataset_name: cifar10
val_split: .1
cache_features: True
feature_cache_dir: null
num_workers: 0

dino_model_name: 'dinov2_vits14' # 21 M params - 384 dimensions
# dino_model_name: 'dinov2_vitb14' # 86 M params - 768 dimensions
# dino_model_name: 'dinov2_vitl14' # 300 M params - 1024 dimensions
# dino_model_name: 'dinov2_vitg14' # 1100 M params - 1536 dimensions

al:
  strategy: perf_dal_oracle
  subset_size: 1000
  init_method: random
  num_init: null
  acq_size: 10
  num_acq: 20
  device: cpu
  optimal:
    num_batches: 100
    strategies: [random,typiclust,dropquery,bait]
    strat_subset_size: 1000
    vary_strat_subset_size: False
    strat_ratio: equal
    num_mc_labels: 5
    look_ahead: true_labels 
    perf_estimation: test_ds
    loss: zero_one
    retraining: train
    num_retraining_epochs: 50
    update_gamma: 10

model:
  name: laplace
  num_epochs: 50
  train_batch_size: 64
  predict_batch_size: 128
  mean_field_factor: 0.4
  mc_samples: 10_000

optimizer: 
  name: SGD
  lr: 1e-2
  weight_decay: 1e-4
  momentum: 0.9
  nesterov: True
  lr_backbone: 1e-5
  finetune_backbone: False

output_dir: ./output/
hydra:
  run:
    dir: ${output_dir}
  job_logging:
    handlers:
      file:
        mode: w