defaults:
  - _self_
  - model: resnet18
  - dataset: CIFAR10
  - al_strategy: random

al_cycle:
  n_init: 100
  acq_size: 100
  n_acq: 9
  cold_start: True
  init_strategy: random
random_seed: 42
dataset_path: ./data/
val_interval: 25

precomputed_features: False
standardize_precomputed_features: False
precomputed_features_dir: model_features_dict.pth
finetuning: False
finetuning_dir: model_features_dict.pth
finetuning_lr: 1e-5

output_dir: ./output/
hydra:
  run:
    dir: ${output_dir}
  job_logging:
    handlers:
      file:
        mode: w

