defaults:
  - model: resnet18_sngp
  - al_strategy: random

al_cycle:
  n_init: 100
  acq_size: 100
  n_acq: 10
  cold_start: True

dataset: imdb
dataset_path: ./data/
device: cuda

random_seed: 42
val_batch_size: 128
print_freq_eval: 25
print_freq_train: 25

output_dir: ./output/
hydra:
  job:
    chdir: True
  run:
    dir: ${output_dir}
