defaults:
  - model: nlp/bert
  - al_strategy: uncertainty

al_cycle:
  n_init: 100
  acq_size: 100
  n_acq: 10
  cold_start: True

dataset: imdb
dataset_path: ./data/
output_dir: ./output/
device: cuda

random_seed: 42
val_batch_size: 128
print_freq_eval: 25
print_freq_train: 25

hydra:
  job:
    chdir: True
  run:
    dir: ${output_dir}/${dataset}/${model.name}/${now:%Y-%m-%d_%H%M%S}
