defaults:
  - model: resnet18
  - al_strategy: random

al_cycle:
  n_init: 100
  acq_size: 100
  n_acq: 10
  cold_start: True

dataset: CIFAR10
dataset_path: ./data/
device: cuda

random_seed: 42
val_batch_size: 128
print_freq_eval: 100
print_freq_train: 100

output_dir: ./output/
hydra:
  run:
    dir: ${output_dir}
  job_logging:
    handlers:
      file:
        mode: w