defaults:
  - _self_
  - model: 'deterministic'

dataset: CIFAR10 
ood_datasets: ["SVHN"]
n_samples: null
n_epochs: 200
eval_interval: 1
train_batch_size: 64
test_batch_size: 64
device: "cuda"
random_seed: 42
imagenet_path: /mnt/datasets/imagenet/ILSVRC2012/downloads

# Define output dir
output_dir: "./output/"
hydra:
  run:
    dir: ${output_dir}