defaults:
  - _self_
  - model: 'resnet18'

dataset: CIFAR10 
dataset_path: ./data # /mnt/datasets/imagenet/ILSVRC2012/downloads
ood_datasets: ["SVHN"]
n_samples: None
eval_interval: 1
test_batch_size: 64
random_seed: 42
device: "cuda"

# Define output dir
output_dir: "./output/"
hydra:
  run:
    dir: ${output_dir}