defaults:
  - _self_
  - model: resnet18
  - dataset: CIFAR10
  - al_strategy: random

random_seed: 42
val_interval: 25

al_cycle:
  n_init: 10
  acq_size: 10
  n_acq: 19
  cold_start: True

path:
  data_dir: ./data/
  imagenet_dir: ./imagenet/
  output_dir: ./output/
  cache_dir: ./cache/

hydra:
  run:
    dir: ${path.output_dir}
  job_logging:
    handlers:
      file:
        mode: w

