defaults:
  - _self_
  - model: 'resnet18'

dataset: CIFAR10 
dataset_path: /mnt/datasets/
ood_datasets: [SVHN, CIFAR100]
val_interval: 25

random_seed: 42
num_devices: 1

# Define output dir
output_dir: "./output/"
hydra:
  run:
    dir: ${output_dir}
  job_logging:
    handlers:
      file:
        mode: w